import { Inter } from 'next/font/google'
import "./globals.css";
import Provider from "@/utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scrollway",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
        <Provider>
        {children}
        </Provider>
       </body>
    
    </html>
  );
}
